"""add was_roman_urdu to orders

Revision ID: 70381ddfcf1f
Revises: dc0879a23cb4
Create Date: 2026-07-13 18:12:56.585616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70381ddfcf1f'
down_revision: Union[str, Sequence[str], None] = 'dc0879a23cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('was_roman_urdu', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'was_roman_urdu')
    # ### end Alembic commands ###
