import { EmailMessage } from '@/types/oms';

/**
 * Fixtures mirroring the rpa-engine sample emails (app/samples/*.txt) run
 * through the real Phase 1 pipeline — same JSON shapes the live API returns.
 */
export const MOCK_EMAILS: EmailMessage[] = [
  {
    id: 'em-1001',
    sender: 'Ayesha Khan',
    sender_email: 'ayesha.khan@brightretail.pk',
    subject: 'Purchase Order — Office Supplies (PO-2214)',
    body_text: [
      'Dear Sales Team,',
      '',
      'Please process the following order for our Lahore office:',
      '',
      '1. A4 Copy Paper (80gsm, 500 sheets) — 20 reams @ Rs. 1,150 each',
      '2. Ballpoint Pens (blue, box of 50) — 6 boxes @ Rs. 900 each',
      '3. Stapler HD-1200 — 4 units @ Rs. 1,450 each',
      '',
      'Total comes to Rs. 34,200. Deliver to: Bright Retail (Pvt) Ltd,',
      '14-B Gulberg III, Lahore. Payment via bank transfer within 15 days.',
      '',
      'Regards,',
      'Ayesha Khan — Procurement Officer',
    ].join('\n'),
    received_at: '2026-07-12T09:14:00Z',
    source: 'sample',
    classification: {
      predicted_label: 'Order',
      confidence: 0.9542,
      all_scores: { Order: 0.9542, Inquiry: 0.0301, Support: 0.0112, Spam: 0.0045 },
    },
    extraction: {
      customer_name: 'Ayesha Khan',
      customer_email: 'ayesha.khan@brightretail.pk',
      order_items: [
        { description: 'A4 Copy Paper (80gsm, 500 sheets)', quantity: 20, unit_price: 1150 },
        { description: 'Ballpoint Pens (blue, box of 50)', quantity: 6, unit_price: 900 },
        { description: 'Stapler HD-1200', quantity: 4, unit_price: 1450 },
      ],
      total_amount: 34200,
      shipping_address: 'Bright Retail (Pvt) Ltd, 14-B Gulberg III, Lahore',
    },
    field_confidence: {
      customer_name: 0.97,
      customer_email: 0.99,
      total_amount: 0.95,
      shipping_address: 0.92,
      order_items: 0.94,
    },
    status: 'pending_review',
    attachments: [],
  },
  {
    id: 'em-1002',
    sender: 'imran traders',
    sender_email: 'imrantraders88@gmail.com',
    subject: 'order chahiye jaldi',
    body_text: [
      'salam, hume ye cheezen chahiye asap...',
      '',
      'sugar 50kg bag x10, ata 20kg... 15 bags i think',
      'aur cooking oil 5L wala - 12',
      '',
      'rate whatsapp pe bata den. address wohi purana godown wala,',
      'main bazar road sargodha. shukriya',
    ].join('\n'),
    received_at: '2026-07-12T11:47:00Z',
    source: 'sample',
    classification: {
      predicted_label: 'Order',
      confidence: 0.7218,
      all_scores: { Order: 0.7218, Inquiry: 0.2114, Support: 0.0421, Spam: 0.0247 },
    },
    extraction: {
      customer_name: 'Imran Traders',
      customer_email: 'imrantraders88@gmail.com',
      order_items: [
        { description: 'Sugar 50kg bag', quantity: 10, unit_price: null },
        { description: 'Ata 20kg bag', quantity: 15, unit_price: null },
        { description: 'Cooking Oil 5L', quantity: 12, unit_price: null },
      ],
      total_amount: null,
      shipping_address: 'Old godown, Main Bazar Road, Sargodha',
      was_roman_urdu: true,
    },
    field_confidence: {
      customer_name: 0.81,
      customer_email: 0.98,
      total_amount: 0.3,
      shipping_address: 0.55,
      order_items: 0.62,
    },
    status: 'pending_review',
    attachments: [],
  },
  {
    id: 'em-1003',
    sender: 'Bilal Ahmed',
    sender_email: 'bilal.ahmed@metrodistributors.com',
    subject: 'Order + scanned receipt attached',
    body_text: [
      'Hi,',
      '',
      'Placing our weekly order — details are on the attached scanned',
      'receipt from last time, same items and quantities again please.',
      '',
      'Thanks,',
      'Bilal — Metro Distributors',
    ].join('\n'),
    received_at: '2026-07-11T16:05:00Z',
    source: 'sample',
    classification: {
      predicted_label: 'Order',
      confidence: 0.8873,
      all_scores: { Order: 0.8873, Inquiry: 0.0844, Support: 0.0201, Spam: 0.0082 },
    },
    extraction: {
      customer_name: 'Bilal Ahmed',
      customer_email: 'bilal.ahmed@metrodistributors.com',
      order_items: [
        { description: 'Dishwashing Liquid 1L', quantity: 24, unit_price: 385 },
        { description: 'Laundry Detergent 3kg', quantity: 12, unit_price: 1240 },
      ],
      total_amount: 24120,
      shipping_address: null,
    },
    field_confidence: {
      customer_name: 0.95,
      customer_email: 0.99,
      total_amount: 0.78,
      shipping_address: 0.2,
      order_items: 0.71,
    },
    status: 'pending_review',
    attachments: [
      {
        id: 'att-1',
        filename: 'receipt_scanned.png',
        kind: 'image',
        source: require('@/assets/images/splash-icon.png'), // placeholder fixture image
      },
      { id: 'att-2', filename: 'invoice_digital.pdf', kind: 'pdf' },
    ],
  },
  {
    id: 'em-1004',
    sender: 'Sana Malik',
    sender_email: 'sana.malik@outlook.com',
    subject: 'Price and availability?',
    body_text: [
      'Hello,',
      '',
      'Do you stock industrial paper towel rolls? If yes, what is the',
      'price per carton and the minimum order quantity? Also — do you',
      'deliver to Islamabad?',
      '',
      'Thanks, Sana',
    ].join('\n'),
    received_at: '2026-07-11T10:22:00Z',
    source: 'sample',
    classification: {
      predicted_label: 'Inquiry',
      confidence: 0.9105,
      all_scores: { Inquiry: 0.9105, Order: 0.0512, Support: 0.0291, Spam: 0.0092 },
    },
    extraction: null,
    status: 'pending_review',
    attachments: [],
  },
  {
    id: 'em-1005',
    sender: 'Kamran Shah',
    sender_email: 'kamran.shah@citymart.pk',
    subject: 'Damaged goods in order #4471 — need replacement',
    body_text: [
      'To whom it may concern,',
      '',
      'Our last delivery (order #4471) arrived with 6 broken jars and a',
      'torn detergent bag. This is the second time this has happened.',
      'Please arrange replacements this week or refund the damaged items.',
      '',
      'Kamran Shah — City Mart',
    ].join('\n'),
    received_at: '2026-07-10T14:38:00Z',
    source: 'sample',
    classification: {
      predicted_label: 'Support',
      confidence: 0.8677,
      all_scores: { Support: 0.8677, Order: 0.0703, Inquiry: 0.0489, Spam: 0.0131 },
    },
    extraction: null,
    status: 'pending_review',
    attachments: [],
  },
  {
    id: 'em-1006',
    sender: 'Mega Prize Dept',
    sender_email: 'winner@lucky-draw-intl.biz',
    subject: 'CONGRATULATIONS! You won $2,500,000 USD!!!',
    body_text: [
      'DEAR LUCKY WINNER,',
      '',
      'Your email was selected in our international draw! To claim your',
      'prize of $2,500,000 USD send your bank details and a processing',
      'fee of only $99 to the address below IMMEDIATELY...',
    ].join('\n'),
    received_at: '2026-07-10T03:12:00Z',
    source: 'sample',
    classification: {
      predicted_label: 'Spam',
      confidence: 0.9861,
      all_scores: { Spam: 0.9861, Inquiry: 0.0071, Support: 0.0041, Order: 0.0027 },
    },
    extraction: null,
    status: 'pending_review',
    attachments: [],
  },
  {
    id: 'em-1007',
    sender: 'Hassan & Co.',
    sender_email: 'orders@hassanco.pk',
    subject: 'Repeat order — approved last week',
    body_text: [
      'Team,',
      '',
      'Repeat of last week: Green Tea 24-pack x 30 cartons @ Rs. 2,100.',
      'Ship to our Karachi warehouse as usual.',
      '',
      'Hassan',
    ].join('\n'),
    received_at: '2026-07-09T08:55:00Z',
    source: 'sample',
    classification: {
      predicted_label: 'Order',
      confidence: 0.9312,
      all_scores: { Order: 0.9312, Inquiry: 0.0455, Support: 0.0158, Spam: 0.0075 },
    },
    extraction: {
      customer_name: 'Hassan & Co.',
      customer_email: 'orders@hassanco.pk',
      order_items: [{ description: 'Green Tea 24-pack carton', quantity: 30, unit_price: 2100 }],
      total_amount: 63000,
      shipping_address: 'Hassan & Co. warehouse, Karachi',
    },
    field_confidence: {
      customer_name: 0.96,
      customer_email: 0.99,
      total_amount: 0.93,
      shipping_address: 0.68,
      order_items: 0.95,
    },
    status: 'approved',
    attachments: [],
  },
];
